services:
  app:
    build: .
    container_name: it-helpdesk-app
    ports:
      - "3006:3000"
    env_file:
      - .env
    networks:
      - ithelpdesk-net
      
networks:
  ithelpdesk-net:
    external: true